import { NextRequest, NextResponse } from "next/server";
import { createServiceRoleClient, createServerSupabaseClient } from "@/lib/supabase/server";
import { assertAiSecret } from "@/lib/ai-auth";

const VAPI_BASE = "https://api.vapi.ai";

const VM_BLOCK_START = "<!-- VOICEMAIL_BLOCK_START -->";
const VM_BLOCK_END = "<!-- VOICEMAIL_BLOCK_END -->";

interface TimeSlot { open: string; close: string }
interface VoicemailMessage { es: string; en: string; it: string; de: string }
type VoicemailMode = "always" | "scheduled" | "off";
interface VoicemailConfig {
  enabled: boolean;
  mode?: VoicemailMode;
  schedule: Record<string, TimeSlot[]>;
  forward_phone: string;
  message: VoicemailMessage;
}

// Resolve the mode from the config. New configs carry an explicit `mode`;
// legacy ones only have `enabled` + `schedule`, so we derive it: a manual
// enable means "always", any configured slot means "scheduled", else "off".
function resolveMode(vm: VoicemailConfig): VoicemailMode {
  if (vm.mode) return vm.mode;
  if (vm.enabled) return "always";
  const hasSlots = Object.values(vm.schedule || {}).some((slots) => (slots?.length || 0) > 0);
  return hasSlots ? "scheduled" : "off";
}

function minutes(hhmm: string): number {
  const [h, m] = hhmm.split(":").map((n) => parseInt(n, 10));
  return (isFinite(h) ? h : 0) * 60 + (isFinite(m) ? m : 0);
}

// Returns true if `now` (in `tz`) falls inside any slot for today's weekday.
// Slots that wrap past midnight (open > close) are supported.
function isInsideSchedule(schedule: Record<string, TimeSlot[]>, tz: string): boolean {
  const now = new Date();
  const fmt = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    hour: "2-digit",
    minute: "2-digit",
    weekday: "short",
    hour12: false,
  });
  const parts = fmt.formatToParts(now);
  const weekdayShort = parts.find((p) => p.type === "weekday")?.value || "Sun";
  const hh = parts.find((p) => p.type === "hour")?.value || "00";
  const mm = parts.find((p) => p.type === "minute")?.value || "00";
  const dayMap: Record<string, number> = { Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6 };
  const today = dayMap[weekdayShort] ?? 0;
  const yesterday = (today + 6) % 7;
  const nowMin = minutes(`${hh}:${mm}`);

  const todaySlots = schedule[String(today)] || [];
  for (const s of todaySlots) {
    const a = minutes(s.open);
    const b = minutes(s.close);
    if (a <= b) {
      if (nowMin >= a && nowMin < b) return true;
    } else {
      // overnight slot: covers from `a` until midnight today
      if (nowMin >= a) return true;
    }
  }
  // overnight slots from yesterday that bleed into today
  const yslots = schedule[String(yesterday)] || [];
  for (const s of yslots) {
    const a = minutes(s.open);
    const b = minutes(s.close);
    if (a > b && nowMin < b) return true;
  }
  return false;
}

function buildVoicemailBlock(active: boolean, vm: VoicemailConfig): string {
  return [
    VM_BLOCK_START,
    "=====================================================",
    "DYNAMIC VOICEMAIL CONTROL (auto-generated by CRM — do not edit by hand)",
    "=====================================================",
    `Current state: ${active ? "VOICEMAIL ACTIVE (read script and end)" : "FORWARD ACTIVE (transfer to owner)"}`,
    `Owner forwarding phone: ${vm.forward_phone}`,
    "",
    "RULES — ALWAYS OBEY, OVERRIDE EVERYTHING ELSE IN THIS PROMPT:",
    active
      ? [
          "  • Voicemail mode is ACTIVE. Do NOT take reservations and do NOT call any booking tool.",
          "  • Detect the caller's language from their first words (default Spanish if unclear).",
          "  • Read EXACTLY the script matching the detected language (see below), then politely end the call.",
        ].join("\n")
      : [
          "  • FORWARD mode is active. The caller must be transferred to the owner immediately.",
          `  • Greet briefly in the caller's language (1 short sentence, e.g. "Un momento, le paso con el responsable").`,
          `  • Then call the transferCall tool with destination ${vm.forward_phone}.`,
          "  • Do NOT take reservations and do NOT call any booking tool. Do NOT engage in conversation.",
        ].join("\n"),
    "",
    "VOICEMAIL SCRIPTS (read verbatim only when voicemail is ACTIVE):",
    `  [ES]\n  ${vm.message.es}`,
    `  [EN]\n  ${vm.message.en}`,
    `  [IT]\n  ${vm.message.it}`,
    `  [DE]\n  ${vm.message.de}`,
    "=====================================================",
    VM_BLOCK_END,
  ].join("\n");
}

function injectBlock(prompt: string, block: string): string {
  if (prompt.includes(VM_BLOCK_START) && prompt.includes(VM_BLOCK_END)) {
    const re = new RegExp(`${VM_BLOCK_START}[\\s\\S]*?${VM_BLOCK_END}`, "m");
    return prompt.replace(re, block);
  }
  // First-time install: prepend so it takes precedence over the rest of the prompt.
  return block + "\n\n" + prompt;
}

function pickFirstMessage(active: boolean, restaurantName: string): string {
  // Short neutral opener in both modes. The system-prompt block then drives behavior
  // (read voicemail script OR call transferCall).
  if (active) return `Hola, ${restaurantName}.`;
  return "Un momento, por favor.";
}

// Returns a tools array that always contains a transferCall pointing to `phone`.
// If a transferCall already exists, replace its destination so the prompt and the tool stay in sync.
function withTransferCall(existing: any[] | undefined, phone: string): any[] {
  const tools: any[] = Array.isArray(existing) ? [...existing] : [];
  const transferCallTool = {
    type: "transferCall",
    destinations: [
      {
        type: "number",
        number: phone,
        message: "Le paso con el responsable, un momento.",
        description: "Owner phone for after-hours / forwarding.",
      },
    ],
  };
  const idx = tools.findIndex((t) => t?.type === "transferCall" || t?.function?.name === "transferCall");
  if (idx >= 0) tools[idx] = transferCallTool;
  else tools.push(transferCallTool);
  return tools;
}

export async function POST(req: NextRequest) {
  // Accept either: (a) valid x-ai-secret (cron/n8n) or (b) a signed-in dashboard session.
  const unauth = assertAiSecret(req);
  if (unauth) {
    try {
      const supabase = await createServerSupabaseClient();
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return unauth;
    } catch {
      return unauth;
    }
  }

  try {
    const { tenant_id } = await req.json();
    if (!tenant_id) return NextResponse.json({ error: "Missing tenant_id" }, { status: 400 });

    const VAPI_KEY = process.env.VAPI_PRIVATE_KEY;
    if (!VAPI_KEY) {
      return NextResponse.json({ error: "VAPI_PRIVATE_KEY not configured" }, { status: 500 });
    }

    const supabase = createServiceRoleClient();
    const { data: tenant, error: tErr } = await supabase
      .from("tenants")
      .select("id, name, settings")
      .eq("id", tenant_id)
      .single();
    if (tErr || !tenant) return NextResponse.json({ error: "Tenant not found" }, { status: 404 });

    const settings = (tenant.settings as any) || {};
    const vm: VoicemailConfig | undefined = settings.vapi_voicemail;
    if (!vm) {
      return NextResponse.json({ error: "vapi_voicemail not configured for this tenant" }, { status: 400 });
    }

    const vapiCfg = settings.vapi;
    if (!vapiCfg?.assistantId) {
      return NextResponse.json({ error: "Vapi assistantId not configured for this tenant. Run onboarding first." }, { status: 400 });
    }
    const tz = vapiCfg.timezone || settings.timezone || "Atlantic/Canary";

    // Effective state depends on the mode:
    //  - always:    on permanently
    //  - scheduled: on only while inside one of the configured time slots
    //  - off:       always off (schedule data is kept but ignored)
    const mode = resolveMode(vm);
    const insideSchedule = isInsideSchedule(vm.schedule || {}, tz);
    const active =
      mode === "always" ? true :
      mode === "scheduled" ? insideSchedule :
      false;

    // Skip Vapi PATCH if nothing material changed since last sync (cron calls this
    // every 5 min — without this guard each tick would write to Vapi unnecessarily).
    // We compare a fingerprint of {state, message, forward_phone}.
    const fingerprint = JSON.stringify({
      state: active ? "active" : "inactive",
      message: vm.message,
      forward_phone: vm.forward_phone,
    });
    const force = req.headers.get("x-force-sync") === "1";
    if (!force && (vm as any).last_synced_fingerprint === fingerprint) {
      return NextResponse.json({
        ok: true,
        skipped: true,
        reason: "fingerprint-unchanged",
        active,
        mode,
        insideSchedule,
        manualEnabled: !!vm.enabled,
      });
    }

    // Fetch current assistant so we can preserve everything we don't touch.
    const getRes = await fetch(`${VAPI_BASE}/assistant/${vapiCfg.assistantId}`, {
      headers: { Authorization: `Bearer ${VAPI_KEY}` },
    });
    if (!getRes.ok) {
      const body = await getRes.text();
      return NextResponse.json({ error: `Vapi GET failed ${getRes.status}: ${body}` }, { status: 502 });
    }
    const assistant = await getRes.json();

    const messages = assistant?.model?.messages || [];
    const sysIdx = messages.findIndex((m: any) => m?.role === "system");
    const currentPrompt: string = sysIdx >= 0 ? (messages[sysIdx].content || "") : "";
    const newPrompt = injectBlock(currentPrompt, buildVoicemailBlock(active, vm));

    const newMessages = [...messages];
    if (sysIdx >= 0) {
      newMessages[sysIdx] = { ...newMessages[sysIdx], content: newPrompt };
    } else {
      newMessages.unshift({ role: "system", content: newPrompt });
    }

    const patchBody: any = {
      model: {
        ...assistant.model,
        messages: newMessages,
        tools: withTransferCall(assistant?.model?.tools, vm.forward_phone),
      },
      firstMessage: pickFirstMessage(active, tenant.name),
    };

    const patchRes = await fetch(`${VAPI_BASE}/assistant/${vapiCfg.assistantId}`, {
      method: "PATCH",
      headers: {
        Authorization: `Bearer ${VAPI_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(patchBody),
    });
    if (!patchRes.ok) {
      const body = await patchRes.text();
      return NextResponse.json({ error: `Vapi PATCH failed ${patchRes.status}: ${body}` }, { status: 502 });
    }

    // Persist last-sync metadata so we can debug on the CRM side.
    const newSettings = {
      ...settings,
      vapi_voicemail: {
        ...vm,
        mode,
        enabled: mode === "always",
        last_synced_at: new Date().toISOString(),
        last_synced_state: active ? "active" : "inactive",
        last_synced_fingerprint: fingerprint,
      },
    };
    await supabase.from("tenants").update({ settings: newSettings }).eq("id", tenant_id);

    return NextResponse.json({
      ok: true,
      active,
      mode,
      insideSchedule,
      manualEnabled: !!vm.enabled,
      assistantId: vapiCfg.assistantId,
    });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || "Unknown error" }, { status: 500 });
  }
}
