import type { BookingStrings } from "@/app/b/[slug]/BookingWidget";

// Guest-facing copy for the booking widget, per tenant locale. Shared by the
// standalone /b/<slug> page AND every site template that embeds the widget
// (the micro-site templates all ship a full-size booking section wired to the
// same /api/public/availability + /api/public/book pipeline).

export type SiteLocale = "it" | "es" | "en" | "de";
export const SITE_LOCALES: SiteLocale[] = ["it", "es", "en", "de"];

export function resolveSiteLocale(raw: unknown): SiteLocale {
  return SITE_LOCALES.includes(raw as SiteLocale) ? (raw as SiteLocale) : "it";
}

export const BOOKING_STRINGS: Record<SiteLocale, BookingStrings & { title: string }> = {
  it: {
    title: "Prenota un tavolo",
    dateLabel: "Data",
    peopleLabel: "Persone",
    timeLabel: "Orario",
    checkBtn: "Vedi disponibilità",
    checking: "Controllo…",
    closedDay: "Quel giorno siamo chiusi. Prova un'altra data.",
    noSlots: "Nessun orario disponibile per quella data. Prova un'altra data.",
    nameLabel: "Nome e cognome",
    phoneLabel: "Cellulare (con prefisso, es. +39…)",
    notesLabel: "Note (opzionale)",
    notesPh: "es. seggiolone, allergie…",
    bookBtn: "Conferma prenotazione",
    booking: "Invio…",
    okConfirmed: "Prenotazione confermata! Riceverai conferma su WhatsApp.",
    okPending: "Richiesta ricevuta! Il ristorante ti confermerà a breve su WhatsApp.",
    okWaitlist: "Il turno è pieno: ti abbiamo messo in lista d'attesa. Ti avvisiamo se si libera un tavolo.",
    okDeposit: "Per completare, paga la caparra qui:",
    depositBtn: "Paga la caparra",
    koFull: "Il turno è al completo. Prova un altro orario o un'altra data.",
    koPhone: "Numero di telefono non valido: usa il prefisso internazionale (es. +39…).",
    koGeneric: "Non siamo riusciti a completare la prenotazione. Riprova.",
    newBooking: "Nuova prenotazione",
  },
  es: {
    title: "Reservar mesa",
    dateLabel: "Fecha",
    peopleLabel: "Personas",
    timeLabel: "Hora",
    checkBtn: "Ver disponibilidad",
    checking: "Comprobando…",
    closedDay: "Ese día estamos cerrados. Prueba otra fecha.",
    noSlots: "No hay horas disponibles para esa fecha. Prueba otra fecha.",
    nameLabel: "Nombre y apellido",
    phoneLabel: "Móvil (con prefijo, p. ej. +34…)",
    notesLabel: "Notas (opcional)",
    notesPh: "p. ej. trona, alergias…",
    bookBtn: "Confirmar reserva",
    booking: "Enviando…",
    okConfirmed: "¡Reserva confirmada! Recibirás la confirmación por WhatsApp.",
    okPending: "¡Solicitud recibida! El restaurante te confirmará en breve por WhatsApp.",
    okWaitlist: "El turno está completo: te hemos puesto en lista de espera. Te avisaremos si se libera una mesa.",
    okDeposit: "Para completar, paga la señal aquí:",
    depositBtn: "Pagar la señal",
    koFull: "El turno está completo. Prueba otra hora u otra fecha.",
    koPhone: "Teléfono no válido: usa el prefijo internacional (p. ej. +34…).",
    koGeneric: "No hemos podido completar la reserva. Inténtalo de nuevo.",
    newBooking: "Nueva reserva",
  },
  en: {
    title: "Book a table",
    dateLabel: "Date",
    peopleLabel: "People",
    timeLabel: "Time",
    checkBtn: "See availability",
    checking: "Checking…",
    closedDay: "We're closed that day. Try another date.",
    noSlots: "No times available for that date. Try another date.",
    nameLabel: "Full name",
    phoneLabel: "Mobile (with country code, e.g. +44…)",
    notesLabel: "Notes (optional)",
    notesPh: "e.g. high chair, allergies…",
    bookBtn: "Confirm booking",
    booking: "Sending…",
    okConfirmed: "Booking confirmed! You'll get a WhatsApp confirmation.",
    okPending: "Request received! The restaurant will confirm shortly on WhatsApp.",
    okWaitlist: "That service is full: we've added you to the waitlist and will let you know if a table frees up.",
    okDeposit: "To complete, pay the deposit here:",
    depositBtn: "Pay the deposit",
    koFull: "That service is fully booked. Try another time or date.",
    koPhone: "Invalid phone number: include the country code (e.g. +44…).",
    koGeneric: "We couldn't complete the booking. Please try again.",
    newBooking: "New booking",
  },
  de: {
    title: "Tisch reservieren",
    dateLabel: "Datum",
    peopleLabel: "Personen",
    timeLabel: "Uhrzeit",
    checkBtn: "Verfügbarkeit prüfen",
    checking: "Wird geprüft…",
    closedDay: "An diesem Tag sind wir geschlossen. Bitte anderes Datum wählen.",
    noSlots: "Keine Zeiten an diesem Datum verfügbar. Bitte anderes Datum wählen.",
    nameLabel: "Vor- und Nachname",
    phoneLabel: "Handy (mit Ländervorwahl, z. B. +49…)",
    notesLabel: "Hinweise (optional)",
    notesPh: "z. B. Hochstuhl, Allergien…",
    bookBtn: "Reservierung bestätigen",
    booking: "Wird gesendet…",
    okConfirmed: "Reservierung bestätigt! Sie erhalten eine WhatsApp-Bestätigung.",
    okPending: "Anfrage erhalten! Das Restaurant bestätigt in Kürze per WhatsApp.",
    okWaitlist: "Die Schicht ist voll: Sie stehen auf der Warteliste. Wir melden uns, wenn ein Tisch frei wird.",
    okDeposit: "Zum Abschluss zahlen Sie hier die Anzahlung:",
    depositBtn: "Anzahlung zahlen",
    koFull: "Die Schicht ist ausgebucht. Bitte andere Zeit oder anderes Datum wählen.",
    koPhone: "Ungültige Telefonnummer: bitte mit Ländervorwahl (z. B. +49…).",
    koGeneric: "Die Reservierung konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
    newBooking: "Neue Reservierung",
  },
};
